### ISSUE TITLE
YahooFinanceService.getTickerData keeps failing

### ISSUE THREAD

**Issue by 19710405** [ivofernandes/yahoo_finance_data_reader#7]
```
flutter: ⛔ Error fetching YahooFinanceCandleData for ticker MSTR, RangeError (index): Invalid value: Not in inclusive range 0..1: 2<…>
```

```
flutter:  ⛔ #1      YahooFinanceService.refreshData (package:yahoo_finance_data_reader/src/daily/services/yahoo_finance_service.dart:111:39)<…>
flutter:  ⛔ #2      YahooFinanceService.getTickerData (package:yahoo_finance_data_reader/src/daily/services/yahoo_finance_service.dart:87:22)<…>
```

```
  Future<List<YahooFinanceCandleData>> refreshData(
    List<YahooFinanceCandleData> pricesParam,
    String symbol, {
    DateTime? startDate,
    bool adjust = false,
  }) async {
    List<YahooFinanceCandleData> prices = pricesParam;

    if (prices.length > 1) {
      // Get one of the lasts dates in the cache, this is not the most recent,
      // because the most recent often is in the middle of the day,
      // and the yahoo finance returns us the current price in the close price column,
      // and for joining dates, we need real instead of the real close prices
      final DateTime lastDate = prices[2].date;
```

Fails at this line:

`final DateTime lastDate = prices[2].date;`

**Comment by ivofernandes** [comment]
I never got this error, can you provide a test to reproduce the error? Or the steps to reproduce the error?

**Comment by 19710405** [comment]
Hmm, it seems to be fine again now, I guess maybe it was just Yahoo server had issues at that time.
